spring.application.name=courseapi

# GraphQL Configuration
spring.graphql.graphiql.enabled=true
spring.graphql.path=/graphql
spring.graphql.schema.printer.enabled=true
#or INFO
logging.level.org.springframework.graphql=INFO
logging.level.com.example.courseapi = DEBUG
server.address=0.0.0.0
server.port = 0
spring.datasource.hikari.maximum-pool-size=5
spring.main.lazy-initialization=true